# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-19 02:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docNum', models.CharField(default=b'', max_length=30)),
                ('title', models.TextField(default=b'')),
                ('agency', models.CharField(default=b'', max_length=30)),
                ('guidelink', models.URLField(default=b'')),
                ('openDate', models.DateField(blank=True, null=True)),
                ('expiryDate', models.DateField(blank=True, null=True)),
                ('parentFOA', models.CharField(default=b'', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Investigator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investigator_id', models.IntegerField(default=0)),
                ('department', models.TextField(default=b'')),
                ('email', models.EmailField(default=b'', max_length=254)),
                ('name', models.TextField(default=b'')),
                ('phone', models.CharField(default=b'', max_length=25)),
                ('picture', models.ImageField(blank=True, null=True, upload_to=b'')),
                ('city', models.TextField(default=b'')),
                ('state', models.TextField(default=b'')),
                ('country', models.TextField(default=b'')),
                ('institution', models.TextField(default=b'')),
                ('office', models.CharField(default=b'', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default=b'')),
                ('medline', models.TextField(default=b'')),
                ('guidelink', models.URLField(default=b'')),
            ],
        ),
    ]
