# Generated by Django 2.1.2 on 2018-11-21 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalTrial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(db_index=True, default=0)),
                ('ctID', models.TextField(default='')),
                ('title', models.TextField(default='')),
                ('ctText', models.TextField(default='')),
                ('guidelink', models.URLField(default='')),
                ('status', models.TextField(default='')),
                ('conditions', models.TextField(default='')),
                ('interventions', models.TextField(default='')),
                ('locations', models.TextField(default='')),
                ('ctVector', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Grant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(db_index=True, default=0)),
                ('grantID', models.TextField(default='')),
                ('guidelink', models.URLField(default='')),
                ('title', models.TextField(default='')),
                ('grantText', models.TextField(default='')),
                ('grantVector', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Investigator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(db_index=True, default=0)),
                ('fName', models.TextField(default='')),
                ('MI', models.TextField(default='')),
                ('lName', models.TextField(default='')),
                ('department', models.TextField(default='')),
                ('position', models.TextField(default='')),
                ('email', models.EmailField(default='', max_length=254)),
                ('city', models.TextField(default='')),
                ('state', models.TextField(default='')),
                ('country', models.TextField(default='')),
                ('office', models.CharField(default='', max_length=50)),
                ('institution', models.TextField(default='')),
                ('phone', models.CharField(default='', max_length=25)),
                ('investigator_tag', models.TextField(default='')),
                ('authorVector', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pmid', models.TextField(default='')),
                ('title', models.TextField(default='')),
                ('abstract', models.TextField(default='')),
                ('affiliation', models.TextField(default='')),
                ('authors', models.TextField(default='')),
                ('source', models.TextField(default='')),
                ('datePublished', models.TextField(default='')),
                ('meshHeadings', models.TextField(default='')),
                ('investigator_tag', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='similarity_matrix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('y_axis', models.IntegerField(default=0)),
                ('x_axis', models.IntegerField(default=0)),
                ('cosine_score', models.DecimalField(decimal_places=10, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='terms_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.TextField(default='')),
                ('termVector', models.TextField(default='')),
            ],
        ),
    ]
