# Generated by Django 2.1.2 on 2018-11-29 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searchFunction', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clinicaltrial',
            old_name='index',
            new_name='indexKey',
        ),
        migrations.RenameField(
            model_name='grant',
            old_name='index',
            new_name='indexKey',
        ),
        migrations.RenameField(
            model_name='investigator',
            old_name='index',
            new_name='indexKey',
        ),
    ]
