# Generated by Django 2.0.6 on 2018-06-29 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchFunction', '0002_auto_20180624_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='abstract',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='publication',
            name='authors',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='publication',
            name='investigator_id',
            field=models.IntegerField(default=0),
        ),
    ]
