# Generated by Django 2.1.2 on 2018-12-16 01:07

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchFunction', '0002_auto_20181129_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicaltrial',
            name='ctVector',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None),
        ),
        migrations.AlterField(
            model_name='grant',
            name='grantVector',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None),
        ),
        migrations.AlterField(
            model_name='investigator',
            name='authorVector',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None),
        ),
    ]
