# Generated by Django 2.0.6 on 2018-07-12 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchFunction', '0003_auto_20180629_2314'),
    ]

    operations = [
        migrations.CreateModel(
            name='author2citation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.TextField(default='')),
                ('citation_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='author_abstracts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.TextField(default='')),
                ('citation_id', models.IntegerField(default=0)),
                ('abstract', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='author_grant_vectors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grantvector', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='authors_grant_documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.TextField(default='')),
                ('grant', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='authors_grants_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.TextField(default='')),
                ('grant_id', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='authors_grants_pairwise_cosine_similarity_matrix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.TextField(default='')),
                ('grant_id', models.IntegerField(default=0)),
                ('cosine_score', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='term_vectors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termvector', models.DecimalField(decimal_places=10, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='terms_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.TextField(default='')),
            ],
        ),
    ]
