# Generated by Django 2.0.6 on 2018-07-17 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchFunction', '0004_author2citation_author_abstracts_author_grant_vectors_authors_grant_documents_authors_grants_list_au'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authors_grants_pairwise_cosine_similarity_matrix',
            old_name='author',
            new_name='x_axis',
        ),
        migrations.RemoveField(
            model_name='authors_grants_pairwise_cosine_similarity_matrix',
            name='grant_id',
        ),
        migrations.AddField(
            model_name='authors_grants_pairwise_cosine_similarity_matrix',
            name='y_axis',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='authors_grants_pairwise_cosine_similarity_matrix',
            name='cosine_score',
            field=models.DecimalField(decimal_places=10, max_digits=10),
        ),
    ]
