# Generated by Django 2.1.2 on 2018-12-16 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searchFunction', '0004_auto_20181216_0208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinicaltrial',
            name='ctText',
        ),
    ]
