# Generated by Django 2.0.6 on 2018-07-20 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchFunction', '0005_auto_20180717_0609'),
    ]

    operations = [
        migrations.DeleteModel(
            name='term_vectors',
        ),
        migrations.AddField(
            model_name='terms_list',
            name='termVector',
            field=models.DecimalField(decimal_places=20, default=0, max_digits=20),
            preserve_default=False,
        ),
    ]
