# Generated by Django 2.1.2 on 2018-12-16 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searchFunction', '0006_auto_20181216_0252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investigator',
            name='MI',
        ),
        migrations.RemoveField(
            model_name='investigator',
            name='country',
        ),
        migrations.RemoveField(
            model_name='investigator',
            name='department',
        ),
        migrations.RemoveField(
            model_name='investigator',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='investigator',
            name='office',
        ),
        migrations.RemoveField(
            model_name='investigator',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='investigator',
            name='position',
        ),
    ]
