# Generated by Django 2.0.6 on 2018-07-25 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchFunction', '0007_auto_20180725_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='author_grant_vectors',
            name='item',
            field=models.TextField(default=''),
        ),
    ]
