# Generated by Django 2.1.2 on 2019-01-02 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchFunction', '0007_auto_20181216_0253'),
    ]

    operations = [
        migrations.AddField(
            model_name='investigator',
            name='fullName',
            field=models.TextField(default=' '),
        ),
    ]
