# Generated by Django 2.0.6 on 2018-07-25 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchFunction', '0008_author_grant_vectors_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author_grant_vectors',
            name='grantvector',
            field=models.DecimalField(decimal_places=10, max_digits=10),
        ),
    ]
