# Generated by Django 2.1.2 on 2019-02-08 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchFunction', '0008_investigator_fullname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investigator',
            old_name='city',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='investigator',
            name='state',
        ),
        migrations.AddField(
            model_name='investigator',
            name='affiliation',
            field=models.TextField(default=' '),
        ),
    ]
