# Generated by Django 2.0.6 on 2018-07-26 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchFunction', '0009_auto_20180725_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terms_list',
            name='termVector',
            field=models.TextField(default=''),
        ),
    ]
