# Generated by Django 2.0.6 on 2018-07-26 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchFunction', '0010_auto_20180726_2135'),
    ]

    operations = [
        migrations.CreateModel(
            name='term_vectors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termVector', models.TextField(default='')),
            ],
        ),
        migrations.RemoveField(
            model_name='terms_list',
            name='termVector',
        ),
    ]
