# Generated by Django 2.0.6 on 2018-07-27 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchFunction', '0011_auto_20180726_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author_grant_vectors',
            name='grantvector',
            field=models.TextField(default=''),
        ),
    ]
