# Generated by Django 2.0.6 on 2018-07-31 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchFunction', '0012_auto_20180727_0117'),
    ]

    operations = [
        migrations.AddField(
            model_name='investigator',
            name='investigator_tag',
            field=models.TextField(default=''),
        ),
    ]
