# Generated by Django 2.0.6 on 2018-08-07 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchFunction', '0013_investigator_investigator_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='authors_grants_list',
            name='grantLink',
            field=models.URLField(default=''),
        ),
    ]
