# Generated by Django 2.0.6 on 2018-08-07 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchFunction', '0014_authors_grants_list_grantlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='grants_links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grantID', models.TextField(default='')),
                ('grantLink', models.URLField(default='')),
            ],
        ),
        migrations.RemoveField(
            model_name='authors_grants_list',
            name='grantLink',
        ),
    ]
