# Generated by Django 2.0.6 on 2018-08-15 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchFunction', '0015_auto_20180807_0539'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investigator',
            old_name='name',
            new_name='Fname',
        ),
        migrations.RemoveField(
            model_name='investigator',
            name='investigator_id',
        ),
        migrations.AddField(
            model_name='investigator',
            name='Lname',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='investigator',
            name='MI',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='investigator',
            name='position',
            field=models.TextField(default=''),
        ),
    ]
