# Generated by Django 2.0.6 on 2018-08-18 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchFunction', '0016_auto_20180815_0046'),
    ]

    operations = [
        migrations.CreateModel(
            name='grant_documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grantTitle', models.TextField(default='')),
                ('grantID', models.TextField(default='')),
                ('grantText', models.TextField(default='')),
                ('grantLink', models.URLField(default='')),
            ],
        ),
        migrations.DeleteModel(
            name='authors_grant_documents',
        ),
        migrations.DeleteModel(
            name='grants_links',
        ),
    ]
