# Generated by Django 2.0.6 on 2018-09-15 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchFunction', '0017_auto_20180818_2303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publication',
            old_name='medline',
            new_name='affiliation',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='guidelink',
        ),
        migrations.AddField(
            model_name='publication',
            name='datePublished',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='publication',
            name='meshHeadings',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='publication',
            name='pmid',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='publication',
            name='source',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='publication',
            name='investigator_id',
            field=models.TextField(default=''),
        ),
    ]
