# Generated by Django 2.0.6 on 2018-09-15 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchFunction', '0018_auto_20180915_0223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author2citation',
            name='citation_id',
            field=models.TextField(default=0),
        ),
    ]
